### PR TITLE
Do not force the ancient OS version dist tag.

### PR DESCRIPTION
**Pull request by adelton**
Just use whatever the OS in question sets.

### CODE REVIEW

**Comment by adelton** [comment]
@mfojtik @soltysh What would be the best way to get this on a radar to get it reviewed?

**Comment by adelton** [comment]
Hello @mfojtik, @soltysh, do we really not want this fixed?

**Comment by mfojtik** [comment]
/reopen

cc @ingvagabund

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
