### PR TITLE
NO-JIRA: adm release: simplify manifest iteration

### PR DESCRIPTION
**Pull request by petr-muller**
Full `imageData` was passed to the callback but existing callbacks only needed the containing directory. Therefore the callback signature can be simplified to `func(directory, content, operator)`

/cc @wking @DavidHurta

### CODE REVIEW

**Review by DavidHurta — APPROVED** [review]

**Comment by petr-muller** [comment]
b06 issues :(

**Comment by petr-muller** [comment]
I think we are hitting [TRT-1900](https://issues.redhat.com/browse/TRT-1900) now

**Pull request merged**
