### PR TITLE
Bug 1860789: Rebase k8s to 1.18.8 to enable approving CSRs on a 4.6 server

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by soltysh** [comment]
e2e-cmd were unrelated to this PR

**Comment by ingvagabund** [comment]
@damemi can you also include https://github.com/openshift/kubernetes-kubectl/pull/33?

**Comment by markmc** [comment]
/retitle Bug 1860789: Rebase k8s to 1.18.8 to enable approving CSRs on a 4.6 server

**Comment by damemi** [comment]
/hold
to include changes from https://github.com/openshift/oc/pull/551#issuecomment-698323304

**Comment by damemi** [comment]
/hold cancel
@soltysh @ingvagabund can you re-tag?

**Comment by soltysh** [comment]
https://github.com/openshift/origin/pull/25560 should help us diagnose what's wrong with e2e-cmd failure

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ashcrow** [comment]
Parent BZ is bumping to 1.19.x k8s while this is bumping to 1.18.8 for approving CSR. Can help me with how these are related?

**Comment by damemi** [comment]
> Parent BZ is bumping to 1.19.x k8s while this is bumping to 1.18.8 for approving CSR. Can help me with how these are related?

@ashcrow this fix was in 1.19 (which was bumped normally for ocp 4.6) and backported to 1.18. Bumping ocp 4.5 to 1.18.8 pulls in the fix

**Pull request merged**
