### PR TITLE
OTA-1174: `upgrade status`: --details shows descriptions and references

### PR DESCRIPTION
**Pull request by petr-muller**
With --details, every insight will have two more fields - description and remediation URL (runbook, documentation...). Output is not a table, but a `oc describe`-like tree output. Move the condition message from the insight summary to its description (which is only shown with --details). Remediation links point to o/runbooks runbook for the matching alert. Condition messages are propagated via an insight description, which is only shown with `--details` in a tree-like output. This allows us to keep linebreaks originally present in the message, we just need to pad each line enough to align it with the indentation of the message start. Incomplete insights are not not actionable enough to show them to the user, so we filter them out while processing.

### CODE REVIEW

**Review by Davoska — CHANGES_REQUESTED** [review]
A well-written code. I even had a good chuckle reading the tests.

I have left some notes, mainly nitpicks and suggestions for small changes. I have not found any bugs. 

Note: Tested locally on the submitted test data.

**Comment by petr-muller** [comment]
Thanks for the feedback, will address. I will hold this PR so that https://github.com/openshift/oc/pull/1689 does not accidentally need to rebase & resolve conflicts.

/hold

**Comment by LalatenduMohanty** [comment]
The PR looks good to me. Once @Davoska 's comments are addressed we can merge this.

**Comment by petr-muller** [comment]
/hold

Adapted to https://github.com/openshift/oc/pull/1689 but I'd like to address some quirks

**Comment by petr-muller** [comment]
I'll need to break this one down :(

**Comment by petr-muller** [comment]
/close

Superseded by https://github.com/openshift/oc/pull/1735 https://github.com/openshift/oc/pull/1736 and https://github.com/openshift/oc/pull/1737

**Pull request closed without merging**
