### PR TITLE
OCPBUGS-41111: vendor: Update openshift/api to pick up v4.17 and v4.18 capability sets

### PR DESCRIPTION
**Pull request by wking**
Catching up with openshift/api#2022.  Generated with:

```console
$ go get github.com/openshift/api@master
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

all using:

```console
$ go version
go version go1.22.2 linux/amd64
```

This addresses [OCPBUGS-41111][2]:

```console
$ cat v4.17-basecap.yaml
---
apiVersion: v1
platform:
  gcp:
    foo: bar
capabilities:
  baselineCapabilitySet: v4.17
$ ./oc adm release extract --install-config v4.17-basecap.yaml --included --credentials-requests --from quay.io/openshift-release-dev/ocp-release:4.17.0-rc.1-x86_64 --to /tmp/test
  error: unrecognized baselineCapabilitySet "v4.17"
```

because [`pkg/cli/admin/release/extract_tools.go` uses the vendored `openshift/api/config/v1` to unpack capabilities][3].

[1]: https://github.com/
[2]: https://issues.redhat.com/browse/OCPBUGS-41111
[3]: https://github.com/openshift/oc/blob/e3584b965787e221a84b81d53107c41d20250047/pkg/cli/admin/release/extract_tools.go#L77

### CODE REVIEW

**Comment by jiajliu** [comment]
pre-merge verify pass

/label qe-approved

**Comment by ardaguclu** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oc/1875/pull-ci-openshift-oc-master-e2e-aws-ovn/1834034427999555584 failure is real and there is an issue after this https://github.com/openshift/api/pull/2017. As far as I understand, this PR is opened due to more targeting to have another backport PR for 4.17?.

I'm investigating the failure now as it will have an impact on rebasing of oc.

**Comment by ardaguclu** [comment]
Since rebasing process hasn't been completed yet, this version of openshift/api hasn't been vendored in other required pieces (especially API Server?). Failing test points out the implications caused by this PR because now oc has new openshift/api and all the commands such as create, run, etc. will send resources with this new `metadata` field for our internal resources in OCP. However, API server will print out a warning just like in the test and that would cause unseen failures in CI (because it hasn't had new `metadata` field yet).

But as far as I understand, the primary goal is to bump 4.17 and there shouldn't be any problem in there. I think, it is better to directly open a PR against release-4.17 and get valid-bug label from staff engineers.

**Comment by wking** [comment]
The vendor bump I was adding here made it into the development branch via eac0d7de9cdc8a5e0 (#1877).

**Pull request closed without merging**
