### PR TITLE
Add user coreydaley as an approver

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by bparees** [comment]
remove adam

**Comment by coreydaley** [comment]
@bparees updated, ptal

**Comment by coreydaley** [comment]
/assign @deads2k 
for approval

**Comment by bparees** [comment]
@soltysh this is probably more yours to approve.  @coreydaley is taking over the team that owns the build stuff, replacing adam.

/unassign @deads2k 
/assign @soltysh

**Comment by coreydaley** [comment]
@soltysh bump

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
