### PR TITLE
[release-4.8] Bug 1974267: make oc logs work with BuildConfig's JenkinsPipeline strategy

### PR DESCRIPTION
**Pull request by soltysh**
This picks https://github.com/openshift/oc/pull/863/ and https://github.com/openshift/oc/pull/860/ to fix units. 

/assign @atiratree

### CODE REVIEW

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff today, may make it tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff today, may make it tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff for today, may make tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *skipping for now, may still be tagged today*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
