### PR TITLE
Add event filter and complete event json to inspect the must-gather results

### PR DESCRIPTION
**Pull request by retroflexer**
The event filter is based on free jqgrid available here: https://github.com/free-jqgrid/jqGrid/. jqGrid is a popular jQuery Plugin for displaying and editing data in tabular form.

This is built on the top of PR https://github.com/openshift/oc/pull/448.

### CODE REVIEW

**Comment by retroflexer** [comment]
If we must make it a single file, we should write all-events.json as a html file with the entire json assigned to a javascript variable. @deads2k

**Comment by deads2k** [comment]
Can this be wired so it has the `all-events.json` pre-loaded when I click the html.  Every little bit helps.

**Comment by deads2k** [comment]
Also, can it inject newlines when it sees `\n`?

`Status for clusteroperator/kube-apiserver changed: Degraded message changed from "NodeControllerDegraded: All master nodes are ready" to "StaticPodsDegraded: pod/kube-apiserver-ip-10-0-198-156.us-west-1.compute.internal container \"kube-apiserver\" is not ready: PodInitializing: \nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-198-156.us-west-1.compute.internal container \"kube-apiserver-cert-regeneration-controller\" is not ready: PodInitializing: \nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-198-156.us-west-1.compute.internal container \"kube-apiserver-cert-syncer\" is not ready: PodInitializing: \nStaticPodsDegraded: pod/kube-apiserver-ip-10-0-198-156.us-west-1.compute.internal container \"kube-apiserver-insecure-readyz\" is not ready: PodInitializing: \nNodeControllerDegraded: All master nodes are ready"	`

as a for instance

**Comment by retroflexer** [comment]
> Also, can it inject newlines when it sees `\n`?
For html, '\n' should be replaced with <br/> (line-break). I will do that.

**Comment by deads2k** [comment]
it worked!

I can't lgtm my own work though.

@retroflexer still need to get those newlines

**Comment by retroflexer** [comment]
> @retroflexer still need to get those newlines

In the browser the newlines are already correctly displayed: For example, look at the uid `6edc7326-8c7f-41b4-b004-70511455db21` in this run:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_oc/451/pull-ci-openshift-oc-master-e2e-cmd/1731

**Comment by soltysh** [comment]
/hold
@retroflexer how this relates to https://github.com/openshift/cluster-debug-tools/pull/5?

**Comment by retroflexer** [comment]
> @retroflexer how this relates to [openshift/cluster-debug-tools#5](https://github.com/openshift/cluster-debug-tools/pull/5)?

The code is similar. The event filter can be used with CI runs, must gather or general events.json file. I put together all those variations in the cluster-debug-tools. Here is the specific use with must-gather events. 

The file https://github.com/openshift/cluster-debug-tools/blob/master/web/event-filter/event-filter-local-jsonstr.html is identical to the code used here in pkg/cli/admin/inspect/eventFilterPage.go.

**Pull request merged**
