### PR TITLE
[release-4.13] AUTH-443: Add OAuth2 Authorization Code Grant Flow for login

### PR DESCRIPTION
**Pull request by liouk**
This PR backports changes from the following PRs:
- https://github.com/openshift/oc/pull/991
- https://github.com/openshift/oc/pull/1402

### CODE REVIEW

**Comment by liouk** [comment]
/hold
contains fake bump

**Comment by liouk** [comment]
/hold cancel
fake bump replaced with merged branch

**Comment by mfojtik** [comment]
/lgtm

until https://github.com/openshift/origin/pull/28396 merges
/hold

**Comment by ardaguclu** [comment]
Why do we backport feature implementation back to 4.13?

**Comment by ardaguclu** [comment]
https://github.com/openshift/oc/pull/991 is the refactoring of the code by migrating to library-go functions and removal of oc duplicates.
https://github.com/openshift/oc/pull/1402 is probably the reason of this backport and it is a new feature with low possibility of breaking current functionality.

/lgtm

**Comment by mfojtik** [comment]
/hold cancel

https://github.com/openshift/origin/pull/28396 passed and merged.

**Pull request merged**
