### PR TITLE
[release-4.14] OCPBUGS-35447: bump go-git to 5.11.0

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by soltysh** [comment]
/override ci/prow/unit 
known failure, fixed in later releases

**Comment by ardaguclu** [comment]
https://github.com/openshift/origin/pull/28881 should fix the `e2e`-agnostic-ovn-cmd` failure.

**Pull request merged**
