### PR TITLE
Bump go to 1.19 in go.mod

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Comment by ingvagabund** [comment]
Checking the history of pull-ci-openshift-oc-master-e2e-aws-builds:
```
{  4 events happened too frequently

event happened 30 times, something is wrong: ns/openshift-controller-manager deployment/controller-manager - reason/ScalingReplicaSet (combined from similar events): Scaled down replica set controller-manager-5bbcfd846c to 1 from 2
event happened 37 times, something is wrong: ns/openshift-controller-manager deployment/controller-manager - reason/ScalingReplicaSet (combined from similar events): Scaled down replica set controller-manager-74566d7b77 to 2 from 3
event happened 45 times, something is wrong: ns/openshift-controller-manager deployment/controller-manager - reason/ScalingReplicaSet (combined from similar events): Scaled down replica set controller-manager-7ff6788f9d to 1 from 2
event happened 22 times, something is wrong: ns/openshift-controller-manager deployment/controller-manager - reason/ScalingReplicaSet (combined from similar events): Scaled down replica set controller-manager-86dc477bb6 to 2 from 3
```

```
Error: error reading Route Table (rtb-0d00df65fd03a11f1): couldn't find resource
```

```
Cluster operator authentication Degraded is True with CustomRouteController_SyncError
```

The first might actually be a valid failure

**Pull request merged**
