### PR TITLE
Bug 1996881: adm catalog mirror: log deprecation message when sqlite-based catalog is in use

### PR DESCRIPTION
**Pull request by joelanford**
With the introduction of file-based configs (aka declarative config), the OLM project is deprecating the use of sqlite-based catalogs.

The `oc adm catalog mirror` tool supports mirroring from sqlite-based images, so we need to log a deprecation warning to inform users that a future release of `oc` will remove support for sqlite-based images.

See https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md#deprecations

Related PR for `opm`: https://github.com/operator-framework/operator-registry/pull/760

### CODE REVIEW

**Comment by joelanford** [comment]
@soltysh could we get an override here for `ci/prow/e2e-agnostic-cmd`?

It seems like that is an unrelated failure, and we're wasting _a lot_ of resources continually re-running it.

**Comment by soltysh** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
since this is optional

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-upgrade 
this is unrelated change

**Pull request merged**
