### PR TITLE
Bug 1801292: support -f for rsh command

### PR DESCRIPTION
**Pull request by soltysh**
This PR  adds support -f for rsh command.

With the first of the following will work just fine:
```
oc rsh nginx cat /etc/resolv.conf 
oc rsh -f pod.yaml cat /etc/resolv.conf 
```

/assign @smarterclayton @mfojtik

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
oc rsh -f pod.yaml  -- cat /etc/resolv.conf 
```

is an api compatibility break because existing users can call that and expect `--` to be passed to the shell argument.  So no, we can't change to support it.

Behavior of `oc rsh` matches `rsh` behavior and rules (as interpreted originally), and we cannot change how arguments are interpreted because that would be break calls

/hold

Other changes are fine, just not supporting `--`.

**Comment by soltysh** [comment]
> Other changes are fine, just not supporting `--`.

Support for `--` was removed, I've even added explicit fail with pointers to rsh API.
/hold cancel

**Comment by soltysh** [comment]
/hold
for debugging why this is failing CI

**Comment by soltysh** [comment]
/hold cancel
I fixed the problem

**Pull request merged**
