### PR TITLE
OCPBUGS-23386: Extract oc also for linux/ppc64le

### PR DESCRIPTION
**Pull request by ardaguclu**
As with https://github.com/openshift/oc/pull/1672 in 4.16, we started compiling oc in linux/ppc64le architecture separately for rhel8 and rhel9. But users can not extract this binary from `oc adm release extract`. This PR
adds oc `linux/ppc64le` in extraction target list to let users can get the correct oc in this architecture.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/cc @ingvagabund 
what is your opinion about this?.

**Comment by ardaguclu** [comment]
According to [here](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.15.0-rc.8/), it will add 48 MB * 3. Would it be reasonable?.

**Comment by ingvagabund** [comment]
The image size should be less. https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.15.0-rc.8/ are archives produced from the image.

**Pull request merged**
