### PR TITLE
Remove already deprecated adm create-kubeconfig command

### PR DESCRIPTION
**Pull request by ardaguclu**
`adm create-kubeconfig` command was deprecated 3 years ago with this commit https://github.com/openshift/oc/pull/435/commits/a2ae72bd4bea89dfadae23bd2514c6e7a6651743

This PR removes this command altogether.

### CODE REVIEW

**Comment by ardaguclu** [comment]
e2e-agnostic-ovn-cmd failure is unrelated;

/test e2e-agnostic-ovn-cmd

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ardaguclu** [comment]
Perm failing jobs might be stabilized;

/retest

**Pull request merged**
