### PR TITLE
NO-JIRA: Consider kubectl version checks only from cli and cli-artifact images

### PR DESCRIPTION
**Pull request by ardaguclu**
Currently, when we bump oc to newer k8s versions, our CI jobs are failing due to kubectl version mismatch error. The reason is that when we bump oc to newer kubectl(i.e. 1.29.0), cli and cli-artifact images manifest this version. On the other hand, other images in other operators have not-bumped kubectl version(i.e. 1.28.2).

This PR only populates kubectl versions in cli and cli-artifact images(because they are the source of truth) but in addition to that this PR checks the other images as well to have a consistency of a rule that all images should match either kubectl version in cli, cli-artifact or match with each other (all versions in other images at least should equal to 1.28.2).

<details>
<summary>valid image sets</summary>

```
cli 1.29.0
cli-artifact 1.29.0
others all 1.28.2
```
```
cli 1.29.0
cli-artifact 1.29.0
others all 1.29.0
```
```
cli 1.29.0
cli-artifact 1.29.0
others 1.28.2
another one  1.29.0
```
</details>

<details>
<summary>invalid image sets</summary>

```
cli 1.29.0
cli-artifact 1.29.0
others 1.28.2
another one 1.27.3
```
```
cli 1.29.0
cli-artifact 1.28.2
others all 1.28.2
```
</details>

This PR is prerequisite of https://github.com/openshift/oc/pull/1655

### CODE REVIEW

**Comment by ardaguclu** [comment]
/hold
until we prove that this patch works.

**Comment by ardaguclu** [comment]
Span up a cluster that contains a combination of this PR and https://github.com/openshift/oc/pull/1656 and all tests passed;

https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1748310181223075840

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
