### PR TITLE
Bug 1795302: initialize auth plugins

### PR DESCRIPTION
**Pull request by soltysh**
Manual cherry-pick of #266 b/c this is touching deps. This time against the correct 4.3 branch. 

/assign @deads2k

### CODE REVIEW

**Comment by soltysh** [comment]
This was rebased so re-applying lgtm back manually.

/bugzilla refresh

**Comment by shawn-hurley** [comment]
@soltysh please rebase to include in 4.3.6

**Comment by soltysh** [comment]
Rebased, self-tagging back.

**Comment by soltysh** [comment]
@shawn-hurley should be good to go

**Pull request merged**
