### PR TITLE
Update containers/image

### PR DESCRIPTION
**Pull request by mtrmac**
... to remove the dependency on compression implementations.

This removes most of the cruft added in #737 .

<s>This is vendoring an unreleased commit from a main branch; a release should happen fairly soon, I'm filing this now so
that I don't forget.</s>

### CODE REVIEW

**Comment by mtrmac** [comment]
Updated to use released containers/image v5.15.0 now.

**Comment by soltysh** [comment]
Picked in https://github.com/openshift/oc/pull/890.

**Pull request closed without merging**
