### PR TITLE
Adjust oc with kubectl and several cleaning items

### PR DESCRIPTION
**Pull request by soltysh**
This PR does the following:

1. fully transition to go-based completion just like k8s has done in https://github.com/kubernetes/kubernetes/pull/96087
2. drop deprecated and experimental commands,  also unused code in several places

/assign @deejross

### CODE REVIEW

**Comment by deejross** [comment]
Does this need to be squashed?

**Comment by soltysh** [comment]
> Does this need to be squashed?

nope, it's intentionally in separate commits to show what's being changed where

**Comment by soltysh** [comment]
/override ci/prow/e2e-agnostic-cmd
which is known to be flaking and is being worked on in parallel

**Comment by soltysh** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
it's not required test

**Pull request merged**
