### PR TITLE
Bug 2051267: pkg/cli/admin/upgrade: Mention --allow-explicit-upgrade next step when appropriate

### PR DESCRIPTION
**Pull request by wking**
Picking #1041 and #1050 back to 4.10.

### CODE REVIEW

**Comment by evakhoni** [comment]
/label qe-approved
pre-merge verified in https://bugzilla.redhat.com/show_bug.cgi?id=2051267#c1

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Pull request merged**
