### PR TITLE
Bug 2090692: Beautify help and align with kubectl output

### PR DESCRIPTION
**Pull request by soltysh**
/assign @deejross @ardaguclu

### CODE REVIEW

**Comment by ardaguclu** [comment]
This PR looks good to me. But tests are failing;
`error calling flagsUsages: file descriptor is not a terminal`

Maybe we should change tests prior to this PR?

**Comment by ardaguclu** [comment]
This looks great. I'll label it after jobs passed.

**Comment by soltysh** [comment]
/hold
test-cmd failures look real

**Pull request merged**
