### PR TITLE
Bug 2026104: Improve errors from image append

### PR DESCRIPTION
**Pull request by dmage**
This PR bumps github.com/openshift/library-go and its dependencies to update the registry client. The new client eagerly checks availability of the blob that helps with error reporting.

Tested with a fake registry: https://gist.github.com/dmage/72bb7b270b76a5faa5ff2a4698a2f27d
using the command
```
./oc image append --insecure --from localhost:8080/foo:latest --to docker.io/dmage/example:foo --image '{"Entrypoint":null}'
```

Error from a previous version:

> error: uploading the source layer sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 failed: Patch "https://registry-1.docker.io/v2/dmage/example/blobs/uploads/1887b852-544d-4a40-a6ba-2979e2b73162?_state=LB2AfV0IeTBqd...MDVaIn0%3D": received unexpected HTTP status: 503 Service Unavailable

Error from the new version:

> error: uploading the source layer sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 failed: unable to access the source layer sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3: received unexpected HTTP status: 503 Service Unavailable

### CODE REVIEW

**Comment by xiuwang** [comment]
Can't build oc binary, with error ， same error in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/996/pull-ci-openshift-oc-master-build-rpms-from-tar/1470882972822409216

vendor/sigs.k8s.io/kustomize/kyaml/fn/runtime/runtimeutil/runtimeutil.go:18:2: cannot find package "." in:
	/go/src/github.com/openshift/oc/vendor/sigs.k8s.io/kustomize/kyaml/order
vendor/sigs.k8s.io/kustomize/kyaml/yaml/rnode.go:17:2: cannot find package "." in:
	/go/src/github.com/openshift/oc/vendor/sigs.k8s.io/kustomize/kyaml/sliceutil
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk:16: build] Error 1

**Comment by dmage** [comment]
/hold
Let's wait until #992 lands.

**Comment by dmage** [comment]
This library-go is already bumped in master.

**Pull request closed without merging**
