### PR TITLE
Bump k8s.io to v0.23.0

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Comment by atiratree** [comment]
go 1.17 is required for the build image, getting:

```
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```

**Comment by atiratree** [comment]
running the CI tests in https://github.com/openshift/oc/pull/993 on a newer image

**Comment by soltysh** [comment]
Replaced with https://github.com/openshift/oc/pull/1001
/close

**Pull request closed without merging**
