### PR TITLE
Bump kubernetes to 1.16.0-rc.2

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sallyom @mfojtik @deads2k

### CODE REVIEW

**Comment by soltysh** [comment]
Only failure is coming from the fact that `kubectl log` was removed (it was deprecated since before k8s 1.0) and tests should be using `kubectl logs`. I've synced with @mfojtik and we'll wait for origin bump to merge first then we will re-kick this and merge only after.

**Comment by soltysh** [comment]
https://github.com/openshift/release/pull/5017 will drop verify-deps which won't pass since we switched to go.mod.

**Comment by soltysh** [comment]
Previous merged, not sure about those numerous aws failures. 
/retest

**Comment by tnozicka** [comment]
the command is `/override` but you should disable the check in release repo when bringing gomod

**Pull request merged**
