### PR TITLE
[release-4.4] Bug 1835739: Fix oc drain to ignore daemonsets and others 

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sallyom 

This brings in https://github.com/kubernetes/kubernetes/pull/87361

### CODE REVIEW

**Comment by ashcrow** [comment]
I was unable to find the parent PR for this merge. Do you mind linking the parent PR in here for verification or is this something that is 4.4 only?

**Comment by soltysh** [comment]
> I was unable to find the parent PR for this merge. Do you mind linking the parent PR in here for verification or is this something that is 4.4 only?

This is only a 4.4 regression, 4.3 and 4.5 work as expected.

**Pull request merged**
