### PR TITLE
WRKLDS-1076: oc idle: Remove redundant endpoint resource modification

### PR DESCRIPTION
**Pull request by ardaguclu**
In the past, oc idle command annotates the **endpoint** resource by modifying it after marking the deployments (or deploymentconfigs or replicasets) as idled.

However, same behavior can be satisfied by annotating the **service** resource (that was added by https://github.com/openshift/oc/pull/720) and this PR removes the endpoint resource modification which is already an unwanted behavior.

### CODE REVIEW

**Comment by ardaguclu** [comment]
It is expected that some tests will fail because they are checking the annotation in endpoints not services https://github.com/openshift/origin/blob/master/test/extended/cli/idle.go

**Comment by ardaguclu** [comment]
This PR is blocked by https://github.com/openshift/origin/pull/28619

**Comment by ardaguclu** [comment]
It seems that combination of this PR and the origin one https://github.com/openshift/origin/pull/28619 succeeded https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1762437001774108672

**Comment by soltysh** [comment]
/hold
until https://github.com/openshift/origin/pull/28619 merges

**Pull request merged**
