### PR TITLE
Get rid of passing oc name to every command

### PR DESCRIPTION
**Pull request by soltysh**
This builds on top of https://github.com/openshift/oc/pull/460 so that other goes first. 
This is cleaning that I've been putting aside for quite some time, hopefully I didn't break anything :wink: 

/assign @sallyom

### CODE REVIEW

**Comment by soltysh** [comment]
Rebased, tagging back manually to move forward.

**Comment by petr-muller** [comment]
/hold

If the test is broken then there's no point in retesting. Either button merge it or `/override` after a failure is reported and then unhold (but Tide may decide to re-run the tests before merge so button merge is probably better).

**Pull request merged**
