### PR TITLE
OCPBUGS-44388: add retry in case of image pull error

### PR DESCRIPTION
**Pull request by andfasano**
Added a retry mechanism to make the command more resilient in case of temporary image pull errors.
From the (fixed) add-nodes job logs:

```
2024-11-08 15:38:12 +(./agent/07_agent_add_node.sh:36): oc adm node-image create --dir ocp/ostest/add-node/ --registry-config /opt/dev-scripts/pull_secret.json --loglevel=2
2024-11-08 15:38:14 I1108 15:38:14.268791   85770 create.go:406] Starting command in pod node-joiner-4n6mq
2024-11-08 15:38:14 I1108 15:38:14.287785   85770 create.go:826] Waiting for pod
...
2024-11-08 15:38:49 I1108 15:38:49.279518   85770 create.go:836] Unable to pull image (ErrImagePull), retrying
2024-11-08 15:38:54 I1108 15:38:54.299369   85770 create.go:826] Waiting for pod
2024-11-08 15:38:54 I1108 15:38:54.299395   85770 create.go:836] Unable to pull image (ErrImagePull), retrying
2024-11-08 15:38:59 I1108 15:38:59.288702   85770 create.go:826] Waiting for pod
2024-11-08 15:38:59 I1108 15:38:59.288736   85770 create.go:836] Unable to pull image (ErrImagePull), retrying
2024-11-08 15:39:04 I1108 15:39:04.290429   85770 create.go:826] Waiting for pod
2024-11-08 15:39:04 I1108 15:39:04.290500   85770 create.go:449] Image generation in progress, please wait
...
2024-11-08 15:40:29 I1108 15:40:29.291542   85770 create.go:449] Image generation in progress, please wait
2024-11-08 15:40:29 I1108 15:40:29.605285   85770 create.go:338] Copying artifacts from node-joiner-4n6mq
2024-11-08 15:40:43 I1108 15:40:43.555202   85770 create.go:317] Command successfully completed
```

### CODE REVIEW

**Comment by andfasano** [comment]
@ardaguclu any idea about the `ci/prow/unit` job failure? Doesn't seem related to the current patch

**Comment by ardaguclu** [comment]
Opened this https://github.com/openshift/oc/pull/1910 to unblock the unit test job.

**Review by rwsu — COMMENTED** [review]
/lgtm

**Comment by andfasano** [comment]
@ardaguclu is it possible to override the failing jobs, since this fix is required for other pending PRs? Thanks

**Comment by ardaguclu** [comment]
> @ardaguclu is it possible to override the failing jobs, since this fix is required for other pending PRs? Thanks

It makes sense. However, I don't have any powers for overriding.

**Pull request merged**
