### PR TITLE
Bug 1874056: Rebase k8s to 1.19.0

### PR DESCRIPTION
**Pull request by damemi**
Previous PR that included patches to master for 1.19-rc.1: https://github.com/openshift/oc/pull/491

openshift/kubernetes fork bump: https://github.com/openshift/kubernetes/pull/324

### CODE REVIEW

**Comment by damemi** [comment]
Update: this is currently waiting on the following 2 PRs:
1. https://github.com/openshift/origin/pull/25468, which depends on
2. https://github.com/openshift/kubernetes/pull/325

After these 2 merge the e2e-cmd failures should be resolved

**Comment by soltysh** [comment]
@damemi this failure is legit:
```
[ERROR] test/cmd/config.sh:46: os::cmd::expect_failure_and_text 'env -u KUBERNETES_SERVICE_HOST oc get buildconfigs --context=""' 'Missing or incomplete configuration info'; 
```
we missed this pick https://github.com/openshift/kubernetes-client-go/pull/18
Re-run go.mod and you should be good to go.

**Comment by damemi** [comment]
Revendored to pull in https://github.com/openshift/kubernetes-client-go/pull/18

**Comment by soltysh** [comment]
Failures are not related with this change.
/override ci/prow/e2e-cmd

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
