### PR TITLE
OCPBUGS-6011: Fix kube version from 1.24.1 to 1.25.2

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR changes the kube version to correct version.

### CODE REVIEW

**Comment by ardaguclu** [comment]
I'd expect last commit should fail in verify step. Because I left kubernetes version to 1.24.1

**Comment by ardaguclu** [comment]
It failed as expected https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/1325/pull-ci-openshift-oc-master-verify/1616016075487449088

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
