### PR TITLE
Bug 1802615: Fix completion verification 

### PR DESCRIPTION
**Pull request by Bowenislandsong**
This fix helps with the verify test.

### CODE REVIEW

**Comment by ecordell** [comment]
@soltysh Does this still need to be done? I see verify passing on other 4.3 PRs

**Comment by soltysh** [comment]
> @soltysh Does this still need to be done? I see verify passing on other 4.3 PRs

If this is working fine, we can safely close the PRs and BZ, @Bowenislandsong mind doing this?

**Comment by Bowenislandsong** [comment]
> > @soltysh Does this still need to be done? I see verify passing on other 4.3 PRs
> 
> If this is working fine, we can safely close the PRs and BZ, @Bowenislandsong mind doing this?

That is weird. I looked up the problem it is stil there... then I ran `make verify` on my local machine
```
hack/verify-generated-completions.sh
hack/lib/../../hack/update-generated-completions.sh: line 7: _output/verify-generated-completions//bash/.files_generated: No such file or directory
Assets generated in _output/verify-generated-completions//bash
hack/lib/../../hack/update-generated-completions.sh: line 7: _output/verify-generated-completions//zsh/.files_generated: No such file or directory
Assets generated in _output/verify-generated-completions//zsh
```

there are still 2 slashes. I am not very sure why `verify` passed.

**Comment by soltysh** [comment]
> there are still 2 slashes. I am not very sure why `verify` passed.

:man_shrugging: I wouldn't care as long as this is working fine :wink: 
/close

**Pull request closed without merging**
