### PR TITLE
Bug 1870361: fish auto-completion

### PR DESCRIPTION
**Pull request by Kevin-Mok**
I copied the completion file from [this repository](https://github.com/evanlucas/fish-kubectl-completions/blob/master/completions/kubectl.fish) which has `fish` completions for `kubectl`. I just replaced all instances of the word `kubectl` with `oc` in the file, and it seems to work fine.

screenshot-2020-08-19_17:00:36

screenshot-2020-08-19_17:05:28

I believe it's for K8s 1.18.3 based on [this commit](https://github.com/evanlucas/fish-kubectl-completions/commit/7bea3e12ff2147961e808b9308b79828aa17b222#diff-442a7fbb18f11338ec763e2c46abe6fd).

### CODE REVIEW

**Comment by Kevin-Mok** [comment]
This is my first issue here. I'm not sure how to fix the invalid bug problem or if I should be assigning @deads2k... :sweat_smile:

**Review by soltysh — CHANGES_REQUESTED** [review]
All of our completions are generated from `hack/update-generated-completions.sh` if you want to see fish supported you'd need to add it there first, so that we can ensure it stays up to date. Adding this one-time will make this file out of date pretty easily. 
/assign
/hold

**Comment by soltysh** [comment]
/ok-to-test

Also I'd consider adding this to kubectl itself, as well.

**Comment by soltysh** [comment]
I'm closing this PR due to inactivity, feel free to re-open when it's updated per previous comments.

**Pull request closed without merging**
