### PR TITLE
Bug 2036940: allow empty files and stdout in oc registry login

### PR DESCRIPTION
**Pull request by atiratree**
fixes https://github.com/openshift/oc/issues/985

- allow empty files in oc registry login
- return support for stdout output in oc registry login 
- add deprecation notices

@soltysh although, this is a regression I would prefer having less validations and passing this change in behaviour / regression to the user. Reasons:
- less complexity
- same behaviour as podman

### CODE REVIEW

**Comment by atiratree** [comment]
also fixed regression for stdout `-` files

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
