### PR TITLE
Revert "WRKLDS-1016: Bump kube dependencies to 1.29.0"

### PR DESCRIPTION
**Pull request by sjenning**
Reverts openshift/oc#1655

Per TRT policy, this broke CI release stream testing and is being reverted

### CODE REVIEW

**Comment by sjenning** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by sjenning** [comment]
/hold

for payload test

**Comment by ardaguclu** [comment]
/approve
in case HCP tests passes with the revert.

**Comment by stbenjam** [comment]
No need for a payload test. 

/skip
/label approved
/lgtm

**Comment by stbenjam** [comment]
/close

CI jobs seem stuck (github issues)

**Pull request merged**
