### PR TITLE
Bug 1989391: Revert to UnstructuredList to fix yaml output

### PR DESCRIPTION
**Pull request by deejross**
When writing out a list of Group objects, the resulting YAML was unusable and causing issues. Reverting back to an UnstructuredList should resolve issues surrounding missing resource fields.

### CODE REVIEW

**Review by soltysh — COMMENTED** [review]
Can you make sure that this change doesn't bring back the problem fixed in https://github.com/openshift/oc/pull/759?

**Comment by deejross** [comment]
Yes, the lines that were added in #759 that fixed that problem are still intact: https://github.com/openshift/oc/pull/759/files#diff-0e9da589427fb76bf92f5a899aa2833a9c16c24ba9183197b9245498a3f807cbR182-R183

**Comment by soltysh** [comment]
/override ci/prow/e2e-agnostic-cmd 
@deejross will look into test-cmd failures

**Pull request merged**
