### PR TITLE
TRT-179 Extend event-filter.html with shareable url & filters

### PR DESCRIPTION
**Pull request by pmtk**
Changes:
- formats html
- bumps `bootstrap` to `5.2.0-beta1`
- bumps `bootstrap-table` to `1.21.1`
- adds a text based time filter (a guide is added to the file)
- adds a regex based filter for other columns
- disables advanced search as it does not support regex filtering (it runs before column-filtering clearing out data causing empty results)
- adds an URL parameters containing filters, paging, and sorting (based on existing `bootstrap-table`'s `addrbar` extension)

### CODE REVIEW

**Comment by dgoodwin** [comment]
This looks terrific @pmtk thanks once again.

It seems to work fine to me.

I am not able to review the code, do we have someone familiar?

**Comment by dgoodwin** [comment]
/assign @soltysh 

Maciej what do you think of this change? This would substantially improve debugging with this tool for TRT.

**Comment by pmtk** [comment]
I had another look at my creation, I think that I need to increase debounce so the url isn't refresh so often that it conflict with text editing. I'll take a look at this during ShiftWeek

**Pull request closed without merging**
