### PR TITLE
Bug 1756454: Separate upgrade flags for safety instead of abusing force

### PR DESCRIPTION
**Pull request by smarterclayton**
The --force flag is dangerous and potentially allows untrusted
content to be upgraded to accidentally. Instead, introduce two
new flags `--allow-explicit-upgrade` (for upgrading to something not
in availableVersions) and `--allow-unsafe-upgrade` (for upgrading
when another upgrade is in progress or the cluster is reporting
an error) and remove those checks from `--force`.

While this is an API change, it is necessary to ensure that users
do not accidentally get access to untrusted content when
performing upgrades across major versions in advance of graph
updates, or when they are upgrading in disconnected environments.

Backport of #109

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
There also this bug https://bugzilla.redhat.com/show_bug.cgi?id=1713263 that states that `--to-latest` and `--force` don't work together correctly? Is that expected @smarterclayton ?

**Comment by jwforres** [comment]
Given the state of CI on master and today's deadline, and that manual testing has been done to verify this on 4.2, overriding bugzilla bot.

**Pull request merged**
