### PR TITLE
[release-4.15] OCPBUGS-31726: Remove some of newapp unit tests relying on external deprecated images

### PR DESCRIPTION
**Pull request by ardaguclu**
This is manual cherry-pick of https://github.com/openshift/oc/pull/1717

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by ardaguclu** [comment]
This is blocked by https://github.com/openshift/origin/pull/28688.
/hold
until origin is merged.

**Comment by ardaguclu** [comment]
/hold
until CI is stable

**Comment by ardaguclu** [comment]
This PR https://github.com/openshift/origin/pull/28688 should fix the agnostic failure

**Comment by xingxingxia** [comment]
Retesting for https://github.com/openshift/oc/pull/1730#issuecomment-2063355248 ...
/retest

**Comment by ardaguclu** [comment]
and the fix for the failing jobs in this PR is https://github.com/openshift/origin/pull/28724 (and master branch https://github.com/openshift/origin/pull/28725)

**Pull request merged**
