### PR TITLE
bring some cert rotation helpers back into 4.10 [fix unit-tests]

### PR DESCRIPTION
**Pull request by stlaz**
contains:
- the server-side apply fix from 4.12
- Arda's fix to the image repository host
- updates generated shell completions

/assign @deads2k

### CODE REVIEW

**Comment by stlaz** [comment]
depends on https://github.com/openshift/origin/pull/27988

**Comment by stlaz** [comment]
/retest-required
the origin PR merged

**Comment by stlaz** [comment]
/retest-required
build failed because of infra

**Comment by deads2k** [comment]
4.11 merged, picking back to 4.10.

**Pull request merged**
