### PR TITLE
[release-4.6] Bug 1891892: Create Windows version information

### PR DESCRIPTION
**Pull request by yselkowitz**
This is a cherry-pick of https://github.com/openshift/oc/pull/623 and https://github.com/openshift/oc/pull/629 for 4.6.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by zhouying7780** [comment]
Pre-merge-verified the issue :  https://bugzilla.redhat.com/show_bug.cgi?id=1891892#c4

**Comment by soltysh** [comment]
Failure in `volumes.sh` is a known problem awaiting final approval in https://github.com/openshift/origin/pull/25831

/override ci/prow/e2e-agnostic-cmd

**Pull request merged**
