### PR TITLE
Oc 4.7 kubernetes 1.20.0 beta.2

### PR DESCRIPTION
**Pull request by ingvagabund**
Following steps in https://github.com/openshift/enhancements/blob/master/enhancements/oc/upgrade_kubernetes.md

### CODE REVIEW

**Comment by ingvagabund** [comment]
`e2e-aws-serial` will not go green until https://github.com/openshift/origin/pull/25715 is merged

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/hold 
for origin PR to land first

**Pull request merged**
