### PR TITLE
WRKLDS-1492: Update k8s dependencies to 1.31.1

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR updates k8s dependencies to 1.31.1 in addition to the required OCP libraries.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/payload 4.18 nightly blocking
/payload 4.18 nightly informing

Only failure should be `[sig-cli] policy scc-subject-review, scc-review [apigroup:authorization.openshift.io][apigroup:user.openshift.io] [Suite:openshift/conformance/parallel]` which will be fixed by https://github.com/openshift/openshift-apiserver/pull/444

**Comment by ardaguclu** [comment]
As far as I can see `e2e-agnostic-ovn-cmd` (image.sh test) is generally unhealthy https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oc/1877/pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd/1834521049262198784

**Comment by ardaguclu** [comment]
Opened this https://github.com/openshift/origin/pull/29104 to fix the problem in e2e-agnostic-ovn-cmd.

**Comment by ardaguclu** [comment]
Failures seem to be unrelated;
/retest

**Comment by ardaguclu** [comment]
@atiratree I saw that 1.31 is in nightlies and I think we can merge this.

**Comment by atiratree** [comment]
The results look good, thanks!
/lgtm

**Pull request merged**
