### PR TITLE
SDN-1174:  Add "oc adm network-tools" command

### PR DESCRIPTION
**Pull request by tssurya**
This commands performs leverages the origin-network-tools image
that contains a series of tests to debug network issues.
It is very similar to must-gather but focused on debugging and diagnosing
network issues, instead of blindly gathering logs.

/cc @rcarrillocruz @astoycos

### CODE REVIEW

**Comment by tssurya** [comment]
/hold 
Need to get the refactoring patch on the network-tools side merged first.

**Comment by rcarrillocruz** [comment]
Is the image sane?
I built the binary from your branch, then:

```
[ricky@fedora oc]$ ./oc adm network-tools                                                                                       
[network-tools      ] OUT imagestreams.image.openshift.io "network-tools" not found
[network-tools      ] OUT                                                                                                      
[network-tools      ] OUT Using network-tools plug-in image: quay.io/openshift/origin-network-tools:latest
[network-tools      ] OUT namespace/openshift-network-tools-gdrwd created
[network-tools      ] OUT clusterrolebinding.rbac.authorization.k8s.io/network-tools-zmz4s created
[network-tools      ] OUT pod for plug-in image quay.io/openshift/origin-network-tools:latest created
[network-tools-r7v9z] POD /usr/bin/network-tools: line 6: oc: command not found
[network-tools-r7v9z] POD INFO: Cluster is using  network plugin         
[network-tools-r7v9z] POD /usr/bin/common: line 69: oc: command not found
[network-tools-r7v9z] POD /usr/bin/common: line 13: oc: command not found
[network-tools-r7v9z] POD INFO: Scheduling network-tools-debug-pod-2obbb on 
[network-tools-r7v9z] POD /usr/bin/common: line 16: oc: command not found
[network-tools-r7v9z] POD /usr/bin/common: line 21: oc: command not found
[network-tools-r7v9z] POD /usr/bin/common: line 23: oc: command not found
```

**Comment by tssurya** [comment]
> Is the image sane?
> I built the binary from your branch, then:
> 
> ```
> [ricky@fedora oc]$ ./oc adm network-tools                                                                                       
> [network-tools      ] OUT imagestreams.image.openshift.io "network-tools" not found
> [network-tools      ] OUT                                                                                                      
> [network-tools      ] OUT Using network-tools plug-in image: quay.io/openshift/origin-network-tools:latest
> [network-tools      ] OUT namespace/openshift-network-tools-gdrwd created
> [network-tools      ] OUT clusterrolebinding.rbac.authorization.k8s.io/network-tools-zmz4s created
> [network-tools      ] OUT pod for plug-in image quay.io/openshift/origin-network-tools:latest created
> [network-tools-r7v9z] POD /usr/bin/network-tools: line 6: oc: command not found
> [network-tools-r7v9z] POD INFO: Cluster is using  network plugin         
> [network-tools-r7v9z] POD /usr/bin/common: line 69: oc: command not found
> [network-tools-r7v9z] POD /usr/bin/common: line 13: oc: command not found
> [network-tools-r7v9z] POD INFO: Scheduling network-tools-debug-pod-2obbb on 
> [network-tools-r7v9z] POD /usr/bin/common: line 16: oc: command not found
> [network-tools-r7v9z] POD /usr/bin/common: line 21: oc: command not found
> [network-tools-r7v9z] POD /usr/bin/common: line 23: oc: command not found
> ```

yea I know, there is deff. something wrong with the quay image. However building the network-tools image itself works well. I don't know where the workflow for the quay is broken.

**Comment by tssurya** [comment]
okay this: https://github.com/openshift/release/pull/17317 should fix the quay image trouble.

**Comment by astoycos** [comment]
Waiting on this ^ to merge before testing

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
Why do we need a complete new command which is copy&paste of `oc adm must-gather`? 
Why not re-use that command? You can already specify either `--image`, `--image-stream` and even command that is being run by default by that image.

**Comment by soltysh** [comment]
If this is specifically for RH engineers then I'd even more encourage to not to add a new command but rather build on the existing. There's `oc debug` which allows you have interactive debugging node sessions with whatever image you want.

**Comment by tssurya** [comment]
> If this is specifically for RH engineers then I'd even more encourage to not to add a new command but rather build on the existing. There's `oc debug` which allows you have interactive debugging node sessions with whatever image you want.

its not specifically for RH engineers only, in future the plan is to extend it to CUs as well. So what we could do is also to add a `--network-debug` flag to oc adm must-gather in which case that tool should pull the network-debug image without making the CU provide that image.

**Comment by soltysh** [comment]
>     1. a host-network pod that we can just spawn up for 60mins to run networking commands in. The `oc debug/node` uses the tool image by default and must-gather spawns a non-hostnetwork pod.

We control the tool image contents, I don't see a reason not to include the necessary debugging tools in that image. 

Other than that, I don't see any particular reason why we need a completely new command. On top of that `oc adm must-gather` has the ability to run arbitrary gathering images, that's how it was created so:
1. I'd advise adding necessary debugging tools to tools image.
2. Provide your own must-gather image, for hands-off debugging/data gathering.
3.

**Comment by tssurya** [comment]
> > ```
> > 1. a host-network pod that we can just spawn up for 60mins to run networking commands in. The `oc debug/node` uses the tool image by default and must-gather spawns a non-hostnetwork pod.
> > ```
> 
> We control the tool image contents, I don't see a reason not to include the necessary debugging tools in that image.
> 

Thanks for the response.

This discussion has happened before with Clayton. Conclusion was; no networking specific tools like ovs/ovn tracer, etc will be put in the tools image, that was one of the main reasons behind creating the new image network-tools. So now all network specific CLI will go there.

Considering the idea of a new CLI is not appealing to repo owners, I'll close this PR.

**Pull request closed without merging**
