### PR TITLE
Bug 1837375: use http.Client.Head instead of tls.Dial to be able to consume proxy settings

### PR DESCRIPTION
**Pull request by soltysh**
/assign @stlaz 
In https://github.com/openshift/oc/commit/eabf7a06457d4c645167cb150167fb3076bb2899 you moved to `tls.Dial` the problem is that it does not use proxy, when one is specified. It needs to wrapped in a full http client to consume one, when needed.

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
this would just bring the old problem back and the BZ has nothing to do with this as it's the DNS lookup that fails

**Comment by soltysh** [comment]
> this would just bring the old problem back and the BZ has nothing to do with this as it's the DNS lookup that fails

Verified just now and only when I'm using 4.4 binary I'm getting:

**Comment by stlaz** [comment]
/hold cancel
/lgtm
I was wrong about the old problem reappearing, I still don't understand the DNS issue reported at the BZ, but that does not matter, this is a good change

**Pull request merged**
