### PR TITLE
[release-4.2] Bug 1802895:  bump(github.com/mtrmac/gpgme): v0.1.2 

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka

### CODE REVIEW

**Comment by soltysh** [comment]
Rebased self-tagging back.

**Comment by crawford** [comment]
@soltysh what's up with the test failure? It looks like there are some trailing spaces in one of those config files.

**Comment by crawford** [comment]
To get the retest bot to settle down, I'm going to put a hold on this PR. Go ahead and remove it once the CI issue has been resolved.

/hold

**Comment by soltysh** [comment]
Fixed that one dependency, self-tagging back.

**Pull request merged**
