### PR TITLE
Drop k8s carries and bump to kubectl v0.24.0-beta-0

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
for https://github.com/openshift/origin/pull/27008 to merge first

**Comment by deejross** [comment]
/lgtm

For this and https://github.com/openshift/origin/pull/27008.

**Comment by soltysh** [comment]
And I also need https://github.com/openshift/origin/pull/27025

**Comment by ardaguclu** [comment]
`e2e-metal-ipi-ovn-ipv6`  test failure is known problem and is not related to this PR.

/lgtm

**Pull request merged**
