### PR TITLE
Bump kubernetes to 1.16.0-beta.1

### PR DESCRIPTION
**Pull request by soltysh**
For review:
- [ ] https://github.com/openshift/oc/commit/c9ce20a9527ccc67ac53124403481f4934f74a97 @dmage Interesting: update code to new docker API 
- [ ] https://github.com/openshift/oc/commit/71be854262e3d159c08c4ab8fa4864abca883d7f @smarterclayton Interesting: update code to new prometheus API
- [ ] https://github.com/openshift/oc/commit/4bcac607f068dc6315be2fef48f7a4c49871ad20 @mfojtik 
Interesting: update handlers 
- [ ] https://github.com/openshift/oc/commit/665fe85e08dbf666b4ddc48669b038bb76864aec @mfojtik Use AuthConfig instead of LazyAuthConfig 

@deads2k and @tnozicka for overall shape

### CODE REVIEW

**Comment by dmage** [comment]
c9ce20a looks ok

**Comment by stbenjam** [comment]
Just curious about the docker version being used: it's a bit old, and is missing the fix for https://github.com/moby/moby/issues/39859, is there a reason a newer version wasn't selected?

**Comment by soltysh** [comment]
> Just curious about the docker version being used: it's a bit old, and is missing the fix for [moby/moby#39859](https://github.com/moby/moby/issues/39859), is there a reason a newer version wasn't selected?

This is coming from kubernetes.

**Comment by soltysh** [comment]
Superseded by https://github.com/openshift/oc/pull/102.

**Pull request closed without merging**
