### PR TITLE
Bug 1949050: Update containers/image

### PR DESCRIPTION
**Pull request by mtrmac**
… in two steps:
- Revert the only user of openshift/containers-image to the original repo (still using a very old v3.0.2)
- Update to v5.10.2 (which is relevant to `oc adm verify-image-signature` by adding a new identity mapping feature); sadly, this drags in various compression implementations that are not actually used.

The first part might affect development on Mac, because `go test` and the like (not mediated through `Makefile`) would require manually specifying the `containers_image_openpgp` tag, or installing `gpgme` (`brew install gpgme`).

Implemented as two separate commits, so you can choose to include only the first one. See individual commit messages for details.

### CODE REVIEW

**Comment by mtrmac** [comment]
> * sadly, this drags in various compression implementations that are not actually used.

Filed https://github.com/containers/image/issues/1146 .

**Comment by sttts** [comment]
> manually specifying the containers_image_openpgp tag, or installing gpgme (brew install gpgme).

Do make print a good error message for this?

**Comment by mtrmac** [comment]
`make` just works (uses the tag). (Well, it fails for me because I don’t have some GSS dependencies.)

Things like this, not using `make`, (building that package, or probably anything that depends on it) fail:
```console
% go build -a ./pkg/cli/admin/verifyimagesignature
# github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^~~~~~~~~
1 error generated.
```

**Comment by soltysh** [comment]
I'd like to see https://github.com/openshift/origin/pull/25880 land first, since that will enable verify test. Secondly, can you split the commit with bump from the actual change to oc, I know it's just a single file (`pkg/cli/admin/verifyimagesignature/verify-signature.go`) it's for readability :wink:

**Comment by mtrmac** [comment]
> Secondly, can you split the commit with bump from the actual change to oc

Like this? It’s a module major version bump (although the changes don’t impact this code), so at the middle commit, the repo does not build.

**Comment by soltysh** [comment]
> Like this? It’s a module major version bump (although the changes don’t impact this code), so at the middle commit, the repo does not build.

Prefect! I wouldn't worry about middle build, it's just easier to review when you separate automated changes from manual ones.

**Comment by mtrmac** [comment]
> I'd like to see [openshift/origin#25880](https://github.com/openshift/origin/pull/25880) land first, since that will enable verify test.

This has now been merged.

**Comment by soltysh** [comment]
/bugzilla refresh
/override ci/prow/e2e-agnostic-cmd
the failure is being fixed and is unrelated to this PR

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
