### PR TITLE
Bug 2100702: Use from-release as based image when base digest is invalid

### PR DESCRIPTION
**Pull request by ardaguclu**
In order to default base image, base digest set in `io.openshift.release.base-image-digest` annotation is used. However, in some cases, this digest can be invalid and can cause failing of `release new` command. Because base digest does not refer to any valid image can be used as base image.

For these cases, we can safely use `from-release` image as base image. This PR adds this.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by mfojtik** [comment]
overriding invalid-bug as we don't have 4.12 target release yet.

**Pull request merged**
